from flask import Flask,request,jsonify
import subprocess
import pyrebase
import os
#configration files of firebase storage
config = {
  "apiKey": "AIzaSyAQ-IhBQrDn1--nvAs784rp6nwwzYxQ4T0",
  "authDomain": "live-subtitles-5d360.firebaseapp.com",
  "projectId": "live-subtitles-5d360",
  "storageBucket": "live-subtitles-5d360.appspot.com",
  "messagingSenderId": "257781236147",
  "appId": "1:257781236147:web:041c06709eca6a1af7cbc6",
  "measurementId": "G-NJWR2NHN0L",
  "databaseURL":"https://live-subtitles-5d360-default-rtdb.firebaseio.com/",
  "serviceAccount": "serviceAccountKey.json",
};

firebase_storage = pyrebase.initialize_app(config)
storage = firebase_storage.storage()
app = Flask(__name__)
@app.route("/", methods=['GET'])
def home():
    filename=str(request.args['query'])
    # # print(filename)
    storage.download("videos/{}".format(filename),"video.mp4")
    subprocess.run(["python","model.py"])
    print("video subtitled sucess")
    # file_path = "video_Subtitled.mp4"
    # remote_path = "files_sub/{}".format(filename)
    # storage.child(remote_path).put(file_path)
    # #copying the subtitled video
    subprocess.run(["python","shift.py"])
    # # #removing the files generated by model
    subprocess.run(["python","remove.py"])
    dic={}
    dic['output'] = filename
    return jsonify(dic) 
if __name__ == "__main__":
    app.run()